### PR TITLE
75 fixing the issues kenneth found and brought to our attention

### LINKED ISSUE #75: fixing the issues kenneth found and brought to our attention
its what it says on the tin
also i am ignoring the jabs at my mental state

### PR DESCRIPTION
**Pull request by wwormseason**
should address issues, 6, 8,(also not sure i got them all), 9(not sure if i got all of them), 10, 14, 15, 16, 18, 20, 21, 22, 26, 35, 36, 38, 44, 45, 48, 4 (i think computed is necessary cus its updating), 50, 53, 55, 57, 58, 59, 60, 65, 66, 5, 46

### CODE REVIEW

**Comment by bridgetf7** [comment]
> should address issues, 6, 8,(also not sure i got them all), 9(not sure if i got all of them), 10, 14, 15, 16, 18, 20, 21, 22, 26, 35, 36, 38, 44, 45, 48, 4 (i think computed is necessary cus its updating), 50, 53, 55, 57, 58, 59, 60, 65, 66, 5, 46

Oh my gosh that’s a MOUNTAIN of issues fixed

**Comment by wwormseason** [comment]
> > should address issues, 6, 8,(also not sure i got them all), 9(not sure if i got all of them), 10, 14, 15, 16, 18, 20, 21, 22, 26, 35, 36, 38, 44, 45, 48, 4 (i think computed is necessary cus its updating), 50, 53, 55, 57, 58, 59, 60, 65, 66, 5, 46
> 
> Oh my gosh that’s a MOUNTAIN of issues fixed

well most of htem were quick fixes it was jsut the last two that had me tearing my hair out T-T

**Comment by bridgetf7** [comment]
> > > should address issues, 6, 8,(also not sure i got them all), 9(not sure if i got all of them), 10, 14, 15, 16, 18, 20, 21, 22, 26, 35, 36, 38, 44, 45, 48, 4 (i think computed is necessary cus its updating), 50, 53, 55, 57, 58, 59, 60, 65, 66, 5, 46
> > 
> > 
> > Oh my gosh that’s a MOUNTAIN of issues fixed
> 
> well most of htem were quick fixes it was jsut the last two that had me tearing my hair out T-T

Ayye I’m glad you figured it out

File: frontend/src/components/GamePage/GameArt.vue [hunk 1]
```diff
@@ -55,55 +55,49 @@ import Dialog from 'primevue/dialog'
...
-const answer = ref(1) // which one is ai
-const correct = ref(false)
+const gameAnswer = ref(1) // which one is ai
+const isCorrect = ref(false)
 
-const getFromBackend = async () => {
-  artPieces.value = [await artStore.getRandomArt('human'), await artStore.getRandomArt('ai')]
-  // the only reason this is pulled out is so
-}
 const portraitBools = {
```
Comment (whydoesthecodenotwork) [inline frontend/src/components/GamePage/GameArt.vue]: is portrait bools used anywhere

File: frontend/src/components/GamePage/GameArt.vue [hunk 2]
```diff
@@ -32,16 +32,16 @@
...
     </div>
     <div>
       <div id="result">
         <!-- eslint-disable vue/no-v-model-argument -->
         <Dialog v-model:visible="isVisible" modal>
           <!-- i think v-model:visible is the only way to toggle visibility with this primevue component, so unfortunately were going to have to break an eslint rule -->
-          <p v-if="correct">Your answer is correct!</p>
-          <p v-else>Your answer is incorrect!</p>
+          <p v-if="isCorrect">Your answer is isCorrect!</p>
+          <p v-else>Your answer is inisCorrect!</p>
```
Comment (whydoesthecodenotwork) [inline frontend/src/components/GamePage/GameArt.vue]: sure

File: frontend/src/components/GamePage/GameArt.vue [hunk 3]
```diff
@@ -55,55 +55,49 @@ import Dialog from 'primevue/dialog'
...
         portraitBools[i].value = true
-        console.log(portraitBools[i].value)
       }
     }
   }
 }
 const checkAnswer = (e) => {
-  if (e != answer.value) {
-    correct.value = false
+  if (e != gameAnswer.value) {
```
Comment (whydoesthecodenotwork) [inline frontend/src/components/GamePage/GameArt.vue]: use strict equality `!==` to avoid javascript being weird

File: frontend/src/components/HeaderComponent.vue [hunk 4]
```diff
@@ -1,25 +1,28 @@
...
-          <span class="ml-2">{{ item.label }}</span>
-           put something here to indicate that this is a dropdown i don't know
-        </a> -->
+        <RouterLink v-if="item.route" v-slot="{ href, navigate }" :to="item.route" custom>
+          <span :href="href" v-bind="props.action" @click="navigate">{{ item.label }}</span>
+        </RouterLink>
+        <RouterLink
+          v-if="item.route == null && !signedIn"
+          v-slot="{ href, navigate }"
+          :to="'/sign'"
```
Comment (whydoesthecodenotwork) [inline frontend/src/components/HeaderComponent.vue]: can be `to="/sign"`

File: frontend/src/components/HeaderComponent.vue [hunk 5]
```diff
@@ -1,25 +1,28 @@
...
-          <a :href="href" v-bind="props.action" @click="navigate">
-            <span>{{ item.label }}</span>
-          </a>
-        </router-link>
-        <!--         <a v-else :href="item.url" :target="item.target" v-bind="props.action">
-          <span class="ml-2">{{ item.label }}</span>
-           put something here to indicate that this is a dropdown i don't know
-        </a> -->
+        <RouterLink v-if="item.route" v-slot="{ href, navigate }" :to="item.route" custom>
+          <span :href="href" v-bind="props.action" @click="navigate">{{ item.label }}</span>
```
Comment (whydoesthecodenotwork) [inline frontend/src/components/HeaderComponent.vue]: this routerlink is kinda confusing; not familiar with v-slot/custom (does it need to be v-slot??????)
but href on a span does nothing i'm pretty sure

File: frontend/src/components/HeaderComponent.vue [hunk 6]
```diff
@@ -1,25 +1,28 @@
...
+        </RouterLink>
+        <RouterLink
+          v-if="item.route == null && !signedIn"
+          v-slot="{ href, navigate }"
+          :to="'/sign'"
+        >
+          <span :href="href" v-bind="props.action" @click="navigate">
+            {{ signedIn ? null : 'Sign In' }}
```
Comment (whydoesthecodenotwork) [inline frontend/src/components/HeaderComponent.vue]: you're already checking `signedIn` in the v-if above

File: frontend/src/components/HeaderComponent.vue [hunk 7]
```diff
@@ -32,7 +35,7 @@ import Menubar from 'primevue/menubar'
 import { useUserStore } from '../stores/user'
 
 const userStore = useUserStore()
-const signedIn = computed(() => !!userStore.currentUser)
+const signedIn = computed(() => userStore.currentUser)
```
Comment (whydoesthecodenotwork) [inline frontend/src/components/HeaderComponent.vue:35]: @kennething why do you hate the !!. are you not excited

File: frontend/src/components/SubmitArtComponent.vue [hunk 8]
```diff
@@ -22,27 +22,36 @@
         >
           <div class="items-center gap-2 mb-4">
             <label id="link-label" class="mr-2">Link to art source:</label>
-            <InputText aria-labelledby="link-label" v-model="links[index]" :disabled="!ok" />
+            <InputText aria-labelledby="link-label" v-model="picture.link" :disabled="!ok" />
```
Comment (whydoesthecodenotwork) [inline frontend/src/components/SubmitArtComponent.vue]: why not `<InputText id="link-label"` and `<label for="link-label"`

File: frontend/src/components/SubmitArtComponent.vue [hunk 9]
```diff
@@ -22,27 +22,36 @@
...
+          </div>
+          <div class="items-center gap-2 mb-4">
+            <label id="link-label" class="mr-2">Artist Name:</label>
```
Comment (whydoesthecodenotwork) [inline frontend/src/components/SubmitArtComponent.vue]: this is not for links

Comment (whydoesthecodenotwork) [reply frontend/src/components/SubmitArtComponent.vue]: also since you have multiple file uploads, you will have duplicate ids `link-label` and `artist-label`. this is probably bad for the label, so consider making ids unique (perchance use index)

File: frontend/src/components/SubmitArtComponent.vue [hunk 10]
```diff
@@ -65,87 +74,79 @@ const imageStore = useImageStore()
...
+  pictures.value.push({
+    link: '',
+    name: '',
+    file: ''
+  })
+}
 
 const userStore = useUserStore()
 const user = userStore.currentUser
 const isAdmin = userStore.isAdmin
```
Comment (whydoesthecodenotwork) [inline frontend/src/components/SubmitArtComponent.vue:104]: legally this could be `const {user, isAdmin} = storeToRefs(userStore)` but this works too

File: frontend/src/components/SubmitArtComponent.vue [hunk 11]
```diff
@@ -65,87 +74,79 @@ const imageStore = useImageStore()
...
-  files.value.push(e.files[0])
-  console.log(files.value)
+const addToast = (severity, summary, detail) => {
   toast.add({
-    severity: 'success',
-    summary: 'Success',
-    detail: 'File successfully uploaded.',
+    severity: severity,
+    summary: summary,
+    detail: detail,
```
Comment (whydoesthecodenotwork) [inline frontend/src/components/SubmitArtComponent.vue]: javascript objects let you do things when key and value are the sameish
try
```
toast.add({
  severity,
  summary,
  detail,
  life: 3000
})
```

File: frontend/src/views/SignFormView.vue [hunk 12]
```diff
@@ -90,14 +90,11 @@ const notMatch = ref(false)
...
 const registerInfo = async () => {
-  if (evilMatch()) return
-  try {
-    const res = await userStore.register(username.value, email.value, password.value)
-    if (res !== null) {
-      signUp.value = !signUp.value
-    }
-  } catch (error) {
-    console.error(error)
+  if ((notMatch.value = password.value !== passwordConfirm.value)) return
```
Comment (whydoesthecodenotwork) [inline frontend/src/views/SignFormView.vue:93]: @kennething what was wrong with calling `evilMatch()`? they're the same thing now just repeated

**Comment by kennething** [comment]
that merge is quite conflicted

File: frontend/src/components/GamePage/GameArt.vue (hunk 2 above)
Comment (kennething) [inline frontend/src/components/GamePage/GameArt.vue]: in is my answer in is correct

File: frontend/src/components/GamePage/GameArt.vue [hunk 13]
```diff
@@ -55,55 +55,49 @@ import Dialog from 'primevue/dialog'
...
 }
 
 const getArt = async () => {
   isVisible.value = false
-  artPieces.value = [await artStore.getRandomArt('human'), await artStore.getRandomArt('ai')]
-  // await getFromBackend()
-  answer.value = 1
+  const humanArt = await artStore.getRandomArt('human')
+  const aiArt = await artStore.getRandomArt('ai')
+  artPieces.value = [humanArt.secure_url, aiArt.secure_url]
```
Comment (kennething) [inline frontend/src/components/GamePage/GameArt.vue]: im glad the url is secure

File: frontend/src/components/GamePage/GameArt.vue (hunk 3 above)
Comment (kennething) [inline frontend/src/components/GamePage/GameArt.vue]: hos !== 100

File: frontend/src/components/GamePage/TabsComponent.vue [hunk 14]
```diff
@@ -2,7 +2,7 @@
   <div id="themes">
     <Tabs value="0" class="w-full">
       <TabList class="flex flex-wrap">
-        <Tab v-for="tab in tabs" :value="tab.value" :key="tab.value" class="sm:text-[2.5vw]">{{
+        <Tab v-for="tab in gameTabs" :value="tab.value" :key="tab.value" class="sm:text-[2.5vw]">{{
```
Comment (kennething) [inline frontend/src/components/GamePage/TabsComponent.vue]: variables dont need to be more than 1 word fyi
i meant they just need to be more than 1 letter mb

File: frontend/src/components/HeaderComponent.vue [hunk 15]
```diff
@@ -1,25 +1,28 @@
...
-        </router-link>
-        <!--         <a v-else :href="item.url" :target="item.target" v-bind="props.action">
-          <span class="ml-2">{{ item.label }}</span>
-           put something here to indicate that this is a dropdown i don't know
-        </a> -->
+        <RouterLink v-if="item.route" v-slot="{ href, navigate }" :to="item.route" custom>
+          <span :href="href" v-bind="props.action" @click="navigate">{{ item.label }}</span>
+        </RouterLink>
+        <RouterLink
+          v-if="item.route == null && !signedIn"
```
Comment (kennething) [inline frontend/src/components/HeaderComponent.vue]: that is an interesting way to make a sign in button

File: frontend/src/components/HeaderComponent.vue (hunk 6 above)
Comment (kennething) [inline frontend/src/components/HeaderComponent.vue]: signedIn cant possibly be true (source: the v-if)
but good on you for handling cosmic bit flips

File: frontend/src/components/SubmitArtComponent.vue [hunk 16]
```diff
@@ -22,27 +22,36 @@
...
+          v-if="isAdmin"
+          :disabled="!ok"
+          label="Upload More"
+          @click="addNewPicture"
+          class="mt-8"
+        />
+        <Button
+          :disabled="!ok"
+          type="submit"
+          :class="`${checked ? 'cursor-pointer' : '!cursor-not-allowed'}  fixed`"
```
Comment (kennething) [inline frontend/src/components/SubmitArtComponent.vue]: `fixed` is fixed and never changes y put it in the `:class`
this is `!ok`

File: frontend/src/components/SubmitArtComponent.vue [hunk 17]
```diff
@@ -65,87 +74,79 @@ const imageStore = useImageStore()
 
 const checked = ref(false)
 const checked2 = ref(false)
-const type = ref('unscreened')
-const links = ref([''])
-const files = ref([])
 const uploading = ref(false)
-const ok = computed(() => checked.value && checked2.value && files.value && !uploading.value)
-const pictures = ref(1)
+const ok = computed(() => checked.value && checked2.value && pictures.value && !uploading.value)
```
Comment (kennething) [inline frontend/src/components/SubmitArtComponent.vue]: sub-3 world record most descriptive variable name any% glitchless

File: frontend/src/components/SubmitArtComponent.vue [hunk 18]
```diff
@@ -65,87 +74,79 @@ const imageStore = useImageStore()
...
 
-async function uploadedFile(e) {
-  files.value.push(e.files[0])
-  console.log(files.value)
+const addToast = (severity, summary, detail) => {
   toast.add({
-    severity: 'success',
-    summary: 'Success',
-    detail: 'File successfully uploaded.',
+    severity: severity,
```
Comment (kennething) [inline frontend/src/components/SubmitArtComponent.vue]: man i wish javascript had a more concise way to make objects that have keys and values with the same name

File: frontend/src/components/SubmitArtComponent.vue [hunk 19]
```diff
@@ -65,87 +74,79 @@ const imageStore = useImageStore()
...
-        summary: 'Warning',
-        detail: "You didn't attach a file.",
-        life: 3000
-      })
-      throw new Error('there is no file')
+const submit = async () => {
+  uploading.value = true
+  if (!user) {
+    addToast('warn', 'Warning', 'You must be logged in to submit art.')
+    throw new Error('not logged in')
```
Comment (kennething) [inline frontend/src/components/SubmitArtComponent.vue]: i love throwing errors and not handling them
if this is to show an error in the console, i wish there was a way to show errors in the console without throwing an error

File: frontend/src/components/SubmitArtComponent.vue [hunk 20]
```diff
@@ -65,87 +74,79 @@ const imageStore = useImageStore()
...
+    formData.append(`tag`, picture.link)
+    formData.append(`name`, picture.name)
+    formData.append(`image`, picture.file)
+  })
+  formData.append('type', 'unscreened')
+
+  const res = await imageStore.uploadImage(formData)
+  if (!res.ok) {
+    addToast('error', 'Error', 'Failed to submit art.')
+    throw new Error((await res.json()).error)
```
Comment (kennething) [inline frontend/src/components/SubmitArtComponent.vue]: i wish there was a way to handle errors
we could call it tri-ketch

or better yet what if we didnt create actual errors and just console dot error

File: frontend/src/components/ThemeComponent.vue [hunk 21]
```diff
@@ -20,7 +20,10 @@
           <div id="colors" @mouseleave="hover = selected">
             <div
               id="color-text"
-              :style="`background-color: var(--p-${hover}-${dark ? 400 : 500}); color: ${dark ? 'white' : 'black'};`"
+              :style="{
+                backgroundColor: `var(--p-${hover}-${dark ? 400 : 500})`,
+                color: dark ? 'white' : 'black'
```
Comment (kennething) [inline frontend/src/components/ThemeComponent.vue:18]: i wish tailwind had a way to change text color based on light/dark mode

File: frontend/src/stores/user.js [hunk 22]
```diff
@@ -1,16 +1,17 @@
...
   const currentUser = ref(null)
   const userId = ref('')
-  const token = ref('')
+  const accessToken = ref('')
   const isAuthenticated = ref(false)
   const isAdmin = ref(false)
 
   // actions
-  const register = async (username: string, email: string, password: string) => {
+  const register = async (username, email, password) => {
```
Comment (kennething) [inline frontend/src/stores/user.js]: i wish there was a way to use the same request and error handling code in multiple places while only having the code in 1 place

File: frontend/src/components/GamePage/GameArt.vue (hunk 13 above)
Comment (whydoesthecodenotwork) [reply frontend/src/components/GamePage/GameArt.vue]: iiiiiiiiirc that's just a cloudinary thing

File: frontend/src/components/GamePage/GameArt.vue (hunk 2 above)
Comment (whydoesthecodenotwork) [reply frontend/src/components/GamePage/GameArt.vue]: ["also im very respectfully ignoring ur spellchecker rec i thibnk typos are funny"](https://github.com/sitechtimes/ai-vs-human-art-frontend/commit/242477312f82d1e77514d85ef1cecd664e143846)

File: frontend/src/components/SubmitArtComponent.vue (hunk 17 above)
Comment (whydoesthecodenotwork) [reply frontend/src/components/SubmitArtComponent.vue]: ok

File: frontend/src/components/SubmitArtComponent.vue (hunk 9 above)
Comment (whydoesthecodenotwork) [reply frontend/src/components/SubmitArtComponent.vue]: oh and ids can't start with a number if you do use index

File: frontend/src/components/SubmitArtComponent.vue (hunk 16 above)
Comment (whydoesthecodenotwork) [reply frontend/src/components/SubmitArtComponent.vue]: does it actually affect anything though

File: frontend/src/components/SubmitArtComponent.vue (hunk 19 above)
Comment (whydoesthecodenotwork) [reply frontend/src/components/SubmitArtComponent.vue]: error is handled through above toast
throwing acts as an early return i guess? idk. it is an error

File: frontend/src/components/SubmitArtComponent.vue (hunk 20 above)
Comment (whydoesthecodenotwork) [reply frontend/src/components/SubmitArtComponent.vue]: toast handle error, !!

File: frontend/src/components/ThemeComponent.vue (hunk 21 above)
Comment (whydoesthecodenotwork) [reply frontend/src/components/ThemeComponent.vue:18]: they should add that to v5

File: frontend/src/stores/user.js (hunk 22 above)
Comment (whydoesthecodenotwork) [reply frontend/src/stores/user.js]: the requestEndpoint spreads..........

**Review by whydoesthecodenotwork — COMMENTED** [review]
uhhhhhhhhh mostly fine

File: frontend/src/components/SubmitArtComponent.vue (hunk 16 above)
Comment (kennething) [reply frontend/src/components/SubmitArtComponent.vue]: no but bad

File: frontend/src/components/HeaderComponent.vue (hunk 7 above)
Comment (kennething) [reply frontend/src/components/HeaderComponent.vue:35]: i am not :angry: :imp: 💢 :rage:

File: frontend/src/components/SubmitArtComponent.vue (hunk 19 above)
Comment (kennething) [reply frontend/src/components/SubmitArtComponent.vue]: how can the toast handle the error if the error is thrown after the toast

File: frontend/src/components/SubmitArtComponent.vue (hunk 20 above)
Comment (kennething) [reply frontend/src/components/SubmitArtComponent.vue]: !!false

File: frontend/src/views/SignFormView.vue (hunk 12 above)
Comment (kennething) [reply frontend/src/views/SignFormView.vue:93]: i didnt comment on evilMatch
this new change is pretty evil(Match)

File: frontend/src/components/GamePage/GameArt.vue (hunk 2 above)
Comment (kennething) [reply frontend/src/components/GamePage/GameArt.vue]: tahts in refrererernce to ehr comit tiltes

File: frontend/src/components/SubmitArtComponent.vue (hunk 19 above)
Comment (whydoesthecodenotwork) [reply frontend/src/components/SubmitArtComponent.vue]: error is shown to the user through toast is what i meant
what would you even put in a catch here

File: frontend/src/components/GamePage/GameArt.vue (hunk 2 above)
Comment (whydoesthecodenotwork) [reply frontend/src/components/GamePage/GameArt.vue]: ih taths smatsr

Comment (wwormseason) [reply frontend/src/components/GamePage/GameArt.vue]: help i dont see this code in gameart.vue?

Comment (wwormseason) [reply frontend/src/components/GamePage/GameArt.vue]: nvm rong branch soprry guys

File: frontend/src/components/HeaderComponent.vue (hunk 5 above)
Comment (wwormseason) [reply frontend/src/components/HeaderComponent.vue]: thats what it is on the primevue website shrug

File: frontend/src/components/SubmitArtComponent.vue (hunk 9 above)
Comment (wwormseason) [reply frontend/src/components/SubmitArtComponent.vue]: made it a class instead

File: frontend/src/components/SubmitArtComponent.vue (hunk 10 above)
Comment (wwormseason) [reply frontend/src/components/SubmitArtComponent.vue:104]: so like i replace all 3 lines with const {user, isAdmin} = storeToRefs(userStore)?

File: frontend/src/components/SubmitArtComponent.vue (hunk 16 above)
Comment (wwormseason) [reply frontend/src/components/SubmitArtComponent.vue]: ok i delted it

File: frontend/src/components/SubmitArtComponent.vue (hunk 10 above)
Comment (whydoesthecodenotwork) [reply frontend/src/components/SubmitArtComponent.vue:104]: did not realize that user is not currentUser, so that wouldn't actually work for user whoops
why does userStore call it currentUser anyway

File: frontend/src/components/HeaderComponent.vue (hunk 5 above)
Comment (whydoesthecodenotwork) [reply frontend/src/components/HeaderComponent.vue]: shrug indeed

File: frontend/src/components/SubmitArtComponent.vue (hunk 9 above)
Comment (whydoesthecodenotwork) [reply frontend/src/components/SubmitArtComponent.vue]: wait now none of the labels are correctly associated with their input
when associated, clicking a label acts as if you clicked the checkbox. also good for not hating blind people

File: frontend/src/components/SubmitArtComponent.vue (hunk 19 above)
Comment (kennething) [reply frontend/src/components/SubmitArtComponent.vue]: no just dont throw an error here
just error the console

Comment (whydoesthecodenotwork) [reply frontend/src/components/SubmitArtComponent.vue]: what's the difference

Comment (kennething) [reply frontend/src/components/SubmitArtComponent.vue]: unhandled errors bad probably

File: frontend/src/components/SubmitArtComponent.vue (hunk 9 above)
Comment (wwormseason) [reply frontend/src/components/SubmitArtComponent.vue]: i forgot about that part oops
ok i nested the input in the label does tha tmake it better chat?

File: frontend/src/components/SubmitArtComponent.vue (hunk 10 above)
Comment (wwormseason) [reply frontend/src/components/SubmitArtComponent.vue:104]: well its storing the user thats sign ed in thsu the current user, idk thats just how i ended up naming it

File: frontend/src/stores/user.js (hunk 22 above)
Comment (wwormseason) [reply frontend/src/stores/user.js]: ?

File: frontend/src/components/SubmitArtComponent.vue (hunk 10 above)
Comment (whydoesthecodenotwork) [reply frontend/src/components/SubmitArtComponent.vue:104]: it works as is so i don't think it's worth renaming currentUser to user

File: frontend/src/stores/user.js (hunk 22 above)
Comment (whydoesthecodenotwork) [reply frontend/src/stores/user.js]: bogdan made a function in regents prep for fetching data called requestEndpoint, which i then stole for my own project (this is the "same request" part)
kenneth later added a tryCatch function for error handling in regents prep (this is the "error handling" part)

Comment (kennething) [reply frontend/src/stores/user.js]: he made then i stole it then u stole it
also im referring to how the functions have the same error handling so that goes back to requestendpoint
don't add tryCatch :skull:
well maybe do cuz its a good system but not necessary for this

Comment (whydoesthecodenotwork) [reply frontend/src/stores/user.js]: i agree i think (i'm not reading all that but i'm happy for you or sorry for your loss)

File: frontend/src/components/ThemeComponent.vue (hunk 21 above)
Comment (wwormseason) [reply frontend/src/components/ThemeComponent.vue:18]: U CODED THAT LAWRENCE????

File: frontend/src/stores/user.js (hunk 22 above)
Comment (wwormseason) [reply frontend/src/stores/user.js]: so should i jsut stela request endpoint
are we plagarizing

File: frontend/src/views/SignFormView.vue (hunk 12 above)
Comment (wwormseason) [reply frontend/src/views/SignFormView.vue:93]: ? can i ignore this

File: frontend/src/components/ThemeComponent.vue (hunk 21 above)
Comment (whydoesthecodenotwork) [reply frontend/src/components/ThemeComponent.vue:18]: i plead the fifth.

File: frontend/src/stores/user.js (hunk 22 above)
Comment (whydoesthecodenotwork) [reply frontend/src/stores/user.js]: @kennething should it spread
(note that request endpoint is ts, and this project is not ts)

File: frontend/src/views/SignFormView.vue (hunk 12 above)
Comment (whydoesthecodenotwork) [reply frontend/src/views/SignFormView.vue:93]: change line 93 back to evilmatch i think?

File: frontend/src/stores/user.js (hunk 22 above)
Comment (kennething) [reply frontend/src/stores/user.js]: yea steal requestendpoint and just get rid of the typescript (i hate type safety)
https://github.com/sitechtimes/regents-prep-app-frontend/blob/dev/utils/fetch.ts#L56

File: frontend/package.json [hunk 23]
```diff
@@ -18,6 +18,7 @@
     "@primevue/themes": "^4.0.7",
     "cloudinary": "^2.5.1",
     "dompurify": "^3.1.7",
+    "frontend": "file:",
```
Comment (kennething) [inline frontend/package.json]: ｆｒｏｎｔｅｎｄ :shipit:

Comment (whydoesthecodenotwork) [reply frontend/package.json]: OIP (39)
